// Kategorien-Katalog fuer "Bieten & Haben" (keine Logik, nur Daten).
// Item = { name: string, emoji: string }
// Pro Kategorie: je ~50 Items, darunter ein paar bewusst alberne Gag-Items.
// Im Browser: window.CATEGORIES. In Node: module.exports.CATEGORIES.

(function () {
  const CATEGORIES = {
    freizeitpark: {
      name: 'Freizeitpark',
      emoji: '🎡',
      gags: ['Erdbeermarmelade', 'Rotkohl', 'Backstein', 'Heizkörper', 'Verlorenes Portemonnaie'],
      items: [
        { name: 'Achterbahn', emoji: '🎢' },
        { name: 'Riesenrad', emoji: '🎡' },
        { name: 'Karussell', emoji: '🎠' },
        { name: 'Geisterbahn', emoji: '👻' },
        { name: 'Autoscooter', emoji: '🚗' },
        { name: 'Zuckerwatte', emoji: '🍭' },
        { name: 'Popcorn-Tüte', emoji: '🍿' },
        { name: 'Riesenrutsche', emoji: '🛝' },
        { name: 'Trampolin-Park', emoji: '🤸' },
        { name: 'Kletterwand', emoji: '🧗' },
        { name: 'Spiegellabyrinth', emoji: '🪞' },
        { name: 'Wasserrutsche', emoji: '💦' },
        { name: 'Piratenschiff', emoji: '⛵' },
        { name: 'Dosenwerfen', emoji: '🥫' },
        { name: 'Heißluftballon', emoji: '🎈' },
        { name: 'Geisterschloss', emoji: '🏰' },
        { name: 'Berg-und-Tal-Bahn', emoji: '🌀' },
        { name: 'Bungee-Trampolin', emoji: '🪂' },
        { name: 'Waffelstand', emoji: '🧇' },
        { name: 'Flossfahrt', emoji: '🚣' },
        { name: 'Riesenrad-Kabine', emoji: '🚠' },
        { name: 'Looping-Bahn', emoji: '🛤️' },
        { name: 'Freifall-Turm', emoji: '🗼' },
        { name: 'Kettenkarussell', emoji: '🎪' },
        { name: 'Geisterauto', emoji: '🚙' },
        { name: 'Sombrero-Fahrt', emoji: '🧢' },
        { name: 'Riesen-Becher', emoji: '🥤' },
        { name: 'Aufblasbare Burg', emoji: '🏯' },
        { name: 'Mini-Hochbahn', emoji: '🚝' },
        { name: 'Nebel-Halle', emoji: '🌫️' },
        { name: 'Gruselecke', emoji: '🕸️' },
        { name: 'Lachsalven-Tunnel', emoji: '😂' },
        { name: 'Magischer Turm', emoji: '🔮' },
        { name: 'Wilde Kugelbahn', emoji: '🔴' },
        { name: 'Elefantenfahrt', emoji: '🐘' },
        { name: 'Zauberlabyrinth', emoji: '🌀' },
        { name: 'Wasserschlacht-Arena', emoji: '🚿' },
        { name: 'Kirmes-Tattoo', emoji: '🖌️' },
        { name: 'Luftballon-Box', emoji: '🎈' },
        { name: 'Pfandflaschen-Wurf', emoji: '🍾' },
        { name: 'Erdbeermarmelade', emoji: '🍓' },
        { name: 'Rotkohl', emoji: '🥗' },
        { name: 'Backstein', emoji: '🧱' },
        { name: 'Heizkörper', emoji: '🌡️' },
        { name: 'Verlorenes Portemonnaie', emoji: '👛' },
        { name: 'Seifenblasen-Kanone', emoji: '🫧' },
        { name: 'Fotowand mit Kirmes-Hut', emoji: '📸' },
        { name: 'Losstand-Tickets', emoji: '🎟️' },
        { name: 'Souvenir-Tassen', emoji: '☕' },
        { name: 'Regentropfen-Garantie', emoji: '🌧️' }
      ]
    },

    pizzeria: {
      name: 'Pizzeria',
      emoji: '🍕',
      gags: ['Tomatensoße im Eimer', 'Geriebener Käse-Berg', 'Pizzakrone', 'Rechnung mit Smiley', 'Pizzavergabe-Klingel'],
      items: [
        { name: 'Margherita', emoji: '🍕' },
        { name: 'Salami-Pizza', emoji: '🍕' },
        { name: 'Belag-Pizza', emoji: '🍕' },
        { name: 'Quattro Formaggi', emoji: '🧀' },
        { name: 'Pizza Hawaii', emoji: '🍍' },
        { name: 'Dicke-Rand-Pizza', emoji: '🍕' },
        { name: 'Mini-Pizza', emoji: '🥧' },
        { name: 'Pizza-Teigrolle', emoji: '🥖' },
        { name: 'Knoblauchbrot', emoji: '🧄' },
        { name: 'Mozzarella-Sticks', emoji: '🧀' },
        { name: 'Bruschetta', emoji: '🍅' },
        { name: 'Caprese-Salat', emoji: '🥗' },
        { name: 'Pizzakarton', emoji: '📦' },
        { name: 'Familien-Pizza', emoji: '🍕' },
        { name: 'Glutenfreie Pizza', emoji: '✨' },
        { name: 'Pizzabäcker', emoji: '👨‍🍳' },
        { name: 'Pizzaofen', emoji: '🔥' },
        { name: 'Pizza-Schneiderad', emoji: '⚙️' },
        { name: 'Rucola-Salat', emoji: '🥗' },
        { name: 'Totale Käse-Überdosis', emoji: '🧀' },
        { name: 'Calzone', emoji: '🥟' },
        { name: 'Pizza-Rolle', emoji: '🍕' },
        { name: 'Supreme-Pizza', emoji: '🍕' },
        { name: 'Veggie-Pizza', emoji: '🥦' },
        { name: 'BBQ-Pizza', emoji: '🍖' },
        { name: 'Pesto-Pizza', emoji: '🌿' },
        { name: 'Meeresfrüchte-Pizza', emoji: '🦐' },
        { name: 'Diavola-Pizza', emoji: '🌶️' },
        { name: 'Ananas-Tornado', emoji: '🍍' },
        { name: 'Pizzakrone', emoji: '👑' },
        { name: 'Cola zur Pizza', emoji: '🥤' },
        { name: 'Zitronen-Eistee', emoji: '🍋' },
        { name: 'Tiramisu', emoji: '🍰' },
        { name: 'Panna Cotta', emoji: '🍮' },
        { name: 'Schokopizza-Dessert', emoji: '🍫' },
        { name: 'Pfeffermühle', emoji: '🧂' },
        { name: 'Oregano-Schneegestöber', emoji: '🌿' },
        { name: 'Pizza-Gutschein', emoji: '🎟️' },
        { name: 'Pizza-Kochmütze', emoji: '🧑‍🍳' },
        { name: 'Riesen-Pizzakorb', emoji: '🧺' },
        { name: 'Tomatensoße im Eimer', emoji: '🍅' },
        { name: 'Geriebener Käse-Berg', emoji: '🧀' },
        { name: 'Oliven-Jackpot', emoji: '🫒' },
        { name: 'Champignon-Pizza', emoji: '🍄' },
        { name: 'Paprika-Regenbogen', emoji: '🫑' },
        { name: 'Pizza-Fahrrad', emoji: '🚴' },
        { name: 'Nachos zum Teilen', emoji: '🫓' },
        { name: 'Dip-Trio', emoji: '🍯' },
        { name: 'Pizzavergabe-Klingel', emoji: '🔔' },
        { name: 'Rechnung mit Smiley', emoji: '🧾' }
      ]
    },

    doener: {
      name: 'Döner-Imbiss',
      emoji: '🌯',
      gags: ['Dönerring', 'Dönerkrone', 'Döner mit Brille', 'Magnet-Döner', 'Himbeer-Döner'],
      items: [
        { name: 'Klassischer Döner', emoji: '🌯' },
        { name: 'Dürüm', emoji: '🌯' },
        { name: 'Lahmacun', emoji: '🫓' },
        { name: 'Pommdöner', emoji: '🍟' },
        { name: 'Dönerbox', emoji: '📦' },
        { name: 'Knoblauchsoße', emoji: '🧄' },
        { name: 'Kräutersoße', emoji: '🌿' },
        { name: 'Scharfe Soße', emoji: '🌶️' },
        { name: 'Currysoße', emoji: '🍛' },
        { name: 'Cocktailsoße', emoji: '🥫' },
        { name: 'Extra Fleisch', emoji: '🍖' },
        { name: 'Falafel-Döner', emoji: '🧆' },
        { name: 'Halloumi-Döner', emoji: '🧀' },
        { name: 'Veggie-Döner', emoji: '🥗' },
        { name: 'Tortilla-Wrap', emoji: '🫓' },
        { name: 'Drehspieß-Glück', emoji: '🍢' },
        { name: 'Zwiebel-Kringel', emoji: '🧅' },
        { name: 'Tomaten-Würfel', emoji: '🍅' },
        { name: 'Salat komplett', emoji: '🥬' },
        { name: 'Weißkraut-Remix', emoji: '🥬' },
        { name: 'Pommes', emoji: '🍟' },
        { name: 'Pommes mit Mayo', emoji: '🥔' },
        { name: 'Pommes mit Ketchup', emoji: '🍅' },
        { name: 'Currywurst', emoji: '🌭' },
        { name: 'Bratwurstbrötchen', emoji: '🌭' },
        { name: 'Köfte', emoji: '🍢' },
        { name: 'Baklava', emoji: '🍯' },
        { name: 'Türkischer Tee', emoji: '🍵' },
        { name: 'Ayran', emoji: '🥛' },
        { name: 'Cola im Glas', emoji: '🥤' },
        { name: 'Fanta-Mix', emoji: '🍹' },
        { name: 'Dönerring', emoji: '💍' },
        { name: 'Dönerkrone', emoji: '👑' },
        { name: 'Salatsoßen-Diamant', emoji: '💎' },
        { name: 'Riesen-Döner', emoji: '🌯' },
        { name: 'Mini-Döner für Anfänger', emoji: '😋' },
        { name: 'Döner-Tüte', emoji: '🛍️' },
        { name: 'Alufolien-Duo', emoji: '🥡' },
        { name: 'Plastikgabel-Deluxe', emoji: '🍴' },
        { name: 'Servietten-Kunst', emoji: '🧻' },
        { name: 'Dönerspieß aus Holz', emoji: '🪵' },
        { name: 'Kräutergewürz-Mix', emoji: '🧂' },
        { name: 'Zitronenecke', emoji: '🍋' },
        { name: 'Minz-Honig-Dip', emoji: '🍯' },
        { name: 'Döner ohne Fleisch', emoji: '🥗' },
        { name: 'Soßentropfen Deluxe', emoji: '🫗' },
        { name: 'Döner mit Brille', emoji: '🤓' },
        { name: 'Geschenktes Papierteller', emoji: '🍽️' },
        { name: 'Magnet-Döner', emoji: '🧲' },
        { name: 'Himbeer-Döner', emoji: '🍓' }
      ]
    },

    burger: {
      name: 'Burgerbude',
      emoji: '🍔',
      gags: ['Burger mit Krone', 'Flausen-Burger', 'Regenbogen-Burger', 'Senf-Schwert', 'Burger ohne Brötchen'],
      items: [
        { name: 'Klassiker-Burger', emoji: '🍔' },
        { name: 'Doppelburger', emoji: '🍔' },
        { name: 'Cheeseburger', emoji: '🧀' },
        { name: 'Chickenburger', emoji: '🍗' },
        { name: 'Veggie-Burger', emoji: '🥬' },
        { name: 'Bacon-Burger', emoji: '🥓' },
        { name: 'Triple-Burger', emoji: '🍔' },
        { name: 'Mini-Burger-Box', emoji: '🍔' },
        { name: 'Riesen-Burger', emoji: '🍔' },
        { name: 'Süßkartoffel-Pommes', emoji: '🍠' },
        { name: 'Krause-Pommes', emoji: '🍟' },
        { name: 'Zwiebelringe', emoji: '🧅' },
        { name: 'Hähnchen-Nuggets', emoji: '🍗' },
        { name: 'Mozzarella Nuggets', emoji: '🧀' },
        { name: 'Kräuter-Dip', emoji: '🥛' },
        { name: 'BBQ-Dip', emoji: '🍖' },
        { name: 'Käsesoße', emoji: '🧀' },
        { name: 'Milchshake', emoji: '🥤' },
        { name: 'Schoko-Milchshake', emoji: '🍫' },
        { name: 'Erdbeer-Milchshake', emoji: '🍓' },
        { name: 'Eiscreme-Bowl', emoji: '🍨' },
        { name: 'Apfel-Stückchen', emoji: '🥧' },
        { name: 'Käsekuchen-Stück', emoji: '🍰' },
        { name: 'Brioche-Brötchen', emoji: '🥐' },
        { name: 'Rettich-Ringe', emoji: '🥒' },
        { name: 'Salat-Krone', emoji: '🥬' },
        { name: 'Gurken-Rad', emoji: '🥒' },
        { name: 'Tomatenscheiben', emoji: '🍅' },
        { name: 'Zwiebel-Glückskugel', emoji: '🧅' },
        { name: 'Cheddar-Blatt', emoji: '🧀' },
        { name: 'Grill-Feuerzeug', emoji: '🔥' },
        { name: 'Burger-Glöckchen', emoji: '🔔' },
        { name: 'Burgerkappe', emoji: '🧢' },
        { name: 'Grillzange', emoji: '🕵️' },
        { name: 'Burger-Serviertablett', emoji: '🛎️' },
        { name: 'Burgerbox aus Karton', emoji: '📦' },
        { name: 'Burgerstempel', emoji: '🌸' },
        { name: 'Drive-In-Überraschung', emoji: '🚀' },
        { name: 'Burger-Lernbox', emoji: '🎓' },
        { name: 'Fritten-Tattoo', emoji: '🖌️' },
        { name: 'Ketchup-Portrait', emoji: '🎨' },
        { name: 'Senf-Schwert', emoji: '⚔️' },
        { name: 'Relish-Becher', emoji: '🥫' },
        { name: 'BBQ-Pinsel', emoji: '🖌️' },
        { name: 'Burger ohne Brötchen', emoji: '🍖' },
        { name: 'Pfanddeckel aus Gold', emoji: '🥤' },
        { name: 'Burger mit Krone', emoji: '👑' },
        { name: 'Halbmond-Fritten', emoji: '🌙' },
        { name: 'Flausen-Burger', emoji: '💨' },
        { name: 'Regenbogen-Burger', emoji: '🌈' }
      ]
    },

    naschwerk: {
      name: 'Naschwerk',
      emoji: '🍩',
      gags: ['Salzbrezel im Süßwarenladen', 'Zerbrochene Zuckerstange', 'Bonbon mit Papier dran', 'Schoko-Figur von dir', 'Glücks-Keks-Haufen'],
      items: [
        { name: 'Berliner', emoji: '🍩' },
        { name: 'Donut mit Glasur', emoji: '🍩' },
        { name: 'Streusel-Donut', emoji: '🍩' },
        { name: 'Zuckerschnecke', emoji: '🥐' },
        { name: 'Hefezopf', emoji: '🥖' },
        { name: 'Krapfen', emoji: '🍩' },
        { name: 'Pfannkuchen-Berg', emoji: '🥞' },
        { name: 'Waffel-Stern', emoji: '🧇' },
        { name: 'Zimtschnecke', emoji: '🌀' },
        { name: 'Marmorkuchen', emoji: '🍰' },
        { name: 'Sahne-Rolle', emoji: '🧁' },
        { name: 'Bienenstich', emoji: '🐝' },
        { name: 'Butterkuchen', emoji: '🧈' },
        { name: 'Streuselkuchen', emoji: '🥮' },
        { name: 'Sandkuchen', emoji: '🍰' },
        { name: 'Schokoladentafel', emoji: '🍫' },
        { name: 'Gummibärchen-Tüte', emoji: '🐻' },
        { name: 'Sauer-Schlangen', emoji: '🍬' },
        { name: 'Lakritz-Schnecke', emoji: '🐌' },
        { name: 'Zuckerstangen-Paar', emoji: '🍭' },
        { name: 'Karnevals-Konfetti', emoji: '🎊' },
        { name: 'Schaumzucker-Herz', emoji: '❤️' },
        { name: 'Wolkentorte', emoji: '☁️' },
        { name: 'Kaiserschmarrn', emoji: '🥞' },
        { name: 'Apfelkuchen', emoji: '🍎' },
        { name: 'Kirschkuchen', emoji: '🍒' },
        { name: 'Rhabarber-Torte', emoji: '🥧' },
        { name: 'Zitronentörtchen', emoji: '🍋' },
        { name: 'Schokokuss', emoji: '🍬' },
        { name: 'Marshmallow-Party', emoji: '🍡' },
        { name: 'Zuckermais-Bonbon', emoji: '🍯' },
        { name: 'Marzipan-Kartoffel', emoji: '🥔' },
        { name: 'Nougat-Bär', emoji: '🐻' },
        { name: 'Pralinen-Set', emoji: '🍫' },
        { name: 'Trüffel-Schatulle', emoji: '🧰' },
        { name: 'Sahnetorte', emoji: '🍰' },
        { name: 'Obstschale', emoji: '🍎' },
        { name: 'Getrocknete Mangos', emoji: '🥭' },
        { name: 'Backwerk-Krone', emoji: '👑' },
        { name: 'Sahne-Spritze', emoji: '💉' },
        { name: 'Bonbon mit Papier dran', emoji: '🍬' },
        { name: 'Zerbrochene Zuckerstange', emoji: '🍭' },
        { name: 'Salzbrezel im Süßwarenladen', emoji: '🥨' },
        { name: 'Überraschungs-Teekanne', emoji: '🫖' },
        { name: 'Konfetti-Muffin', emoji: '🧁' },
        { name: 'Pusteblume-Sahne', emoji: '🌼' },
        { name: 'Karamell-Schleuder', emoji: '🫧' },
        { name: 'Fingerhut-Bonbon', emoji: '🔮' },
        { name: 'Schoko-Figur von dir', emoji: '🫂' },
        { name: 'Glücks-Keks-Haufen', emoji: '🥠' }
      ]
    },

    eisdiele: {
      name: 'Eisdiele',
      emoji: '🍦',
      gags: ['Salz-Eis', 'Eis am Stiel ohne Stiel', 'Sprudel-Nudel-Eis', 'Eis-Delfin', 'Lokomotiv-Eis'],
      items: [
        { name: 'Vanille-Eis', emoji: '🍦' },
        { name: 'Erdbeer-Eis', emoji: '🍓' },
        { name: 'Schoko-Eis', emoji: '🍫' },
        { name: 'Pistazien-Eis', emoji: '🍨' },
        { name: 'Mango-Sorbet', emoji: '🥭' },
        { name: 'Zitronen-Sorbet', emoji: '🍋' },
        { name: 'Blaubeer-Eis', emoji: '🫐' },
        { name: 'Karamell-Eis', emoji: '🍮' },
        { name: 'Gummibär-Eis', emoji: '🧸' },
        { name: 'Eis-Topping-Wirbel', emoji: '🎉' },
        { name: 'Eisbecher Deluxe', emoji: '🍨' },
        { name: 'Sundae-Klassiker', emoji: '🍨' },
        { name: 'Banana Split', emoji: '🍌' },
        { name: 'Sahne-Traum', emoji: '🗽' },
        { name: 'Eis am Stiel', emoji: '🍡' },
        { name: 'Schoko-Traum-Torte', emoji: '🍰' },
        { name: 'Waffel-Becher', emoji: '🍯' },
        { name: 'Krokant-Kuller', emoji: '🥨' },
        { name: 'Heiße Kirschen', emoji: '🍒' },
        { name: 'Schokosauce-Lawine', emoji: '🍫' },
        { name: 'Kokos-Eis', emoji: '🥥' },
        { name: 'Zauber-Schaum', emoji: '🫧' },
        { name: 'Milcheis-Hörnchen', emoji: '🌽' },
        { name: 'Mousse-Soufflé', emoji: '🍮' },
        { name: 'Apfelstrudel-Eis', emoji: '🥧' },
        { name: 'Popcorn-Eis', emoji: '🍿' },
        { name: 'Cola-Rock-Eis', emoji: '🥤' },
        { name: 'Regenbogen-Split', emoji: '🌈' },
        { name: 'Haselnuss-Wolke', emoji: '🌰' },
        { name: 'Wasser-Eis Lolly', emoji: '🧊' },
        { name: 'Kugel-Turm', emoji: '🚢' },
        { name: 'Glitzergranulat', emoji: '✨' },
        { name: 'Blaues Zauber-Eis', emoji: '💙' },
        { name: 'Mango-Maracuja', emoji: '🥭' },
        { name: 'Kirsche obendrauf', emoji: '🍒' },
        { name: 'Vanilleschote', emoji: '🌿' },
        { name: 'Eiskugel-Foto', emoji: '📸' },
        { name: 'Gratis-Löffel', emoji: '🥄' },
        { name: 'Eiswaffel-Set', emoji: '🧇' },
        { name: 'Eisbecher-Krone', emoji: '👑' },
        { name: 'Salz-Eis', emoji: '🧂' },
        { name: 'Eis am Stiel ohne Stiel', emoji: '🥶' },
        { name: 'Sprudel-Nudel-Eis', emoji: '🍜' },
        { name: 'Eis-Delfin', emoji: '🐬' },
        { name: 'Sternenfänger-Eis', emoji: '⭐' },
        { name: 'Himmelsbeere-Eis', emoji: '🔮' },
        { name: 'Wow-Becher', emoji: '😮' },
        { name: 'Mini-Sonne im Becher', emoji: '🌞' },
        { name: 'Lokomotiv-Eis', emoji: '🚂' },
        { name: 'Raketen-Eis-Duo', emoji: '🚀' }
      ]
    },

    kuscheltiere: {
      name: 'Kuscheltiere',
      emoji: '🧸',
      gags: ['Kaffeetasse-Kuschel', 'Teddy mit einem Ohr', 'Armloser Oktopus', 'Knuddelmonster im Anzug', 'Socken-Monster'],
      items: [
        { name: 'Brauner Teddy', emoji: '🧸' },
        { name: 'Weißer Teddy', emoji: '🧸' },
        { name: 'Panda-Kuscheltier', emoji: '🐼' },
        { name: 'Kuschel-Hase', emoji: '🐰' },
        { name: 'Kuschel-Katze', emoji: '🐱' },
        { name: 'Kuschel-Hund', emoji: '🐶' },
        { name: 'Einhorn-Kuscheltier', emoji: '🦄' },
        { name: 'Drachen-Wuschel', emoji: '🐉' },
        { name: 'Dino-Teddy', emoji: '🦖' },
        { name: 'Schlaf-Elefant', emoji: '🐘' },
        { name: 'Pinguin-Plüsch', emoji: '🐧' },
        { name: 'Eisbär-Junior', emoji: '🐻‍❄️' },
        { name: 'Koala-Baby', emoji: '🐨' },
        { name: 'Flamingo-Kissen', emoji: '🦩' },
        { name: 'Otter-Knuddel', emoji: '🦦' },
        { name: 'Fuchs-Freund', emoji: '🦊' },
        { name: 'Wolf-Knuddel', emoji: '🐺' },
        { name: 'Nashorn-Kuschel', emoji: '🦏' },
        { name: 'Kuschel-Affe', emoji: '🐵' },
        { name: 'Koala-Kim', emoji: '🐨' },
        { name: 'Quallen-Quatsch', emoji: '🪼' },
        { name: 'Krake 8 Arme', emoji: '🐙' },
        { name: 'Wal-Wuschel', emoji: '🐳' },
        { name: 'Delfin-Dussi', emoji: '🐬' },
        { name: 'Schildkröte-Sofie', emoji: '🐢' },
        { name: 'Frosch-Hüpfer', emoji: '🐸' },
        { name: 'Schmetterling-Feder', emoji: '🦋' },
        { name: 'Biene-Maja', emoji: '🐝' },
        { name: 'Marienkäfer-Pummel', emoji: '🐞' },
        { name: 'Yeti-Watzke', emoji: '🦍' },
        { name: 'Robbe-Flocke', emoji: '🦭' },
        { name: 'Hörnchen-Hase', emoji: '🐹' },
        { name: 'Waschbär-Racker', emoji: '🦝' },
        { name: 'Igel-Kugel', emoji: '🦔' },
        { name: 'Fledermaus-Batzi', emoji: '🦇' },
        { name: 'Geister-Plüsch', emoji: '👻' },
        { name: 'Skelett-Bruder', emoji: '💀' },
        { name: 'Alien-Basti', emoji: '👽' },
        { name: 'Robbie Roboter', emoji: '🤖' },
        { name: 'Herz-Kissen', emoji: '❤️' },
        { name: 'Teddy mit einem Ohr', emoji: '🧸' },
        { name: 'Knuddelmonster im Anzug', emoji: '🤵' },
        { name: 'Beutelratte-Deluxe', emoji: '🐀' },
        { name: 'Armloser Oktopus', emoji: '🐙' },
        { name: 'Sparschwein-Plüsch', emoji: '🐷' },
        { name: 'Emmi die Ente', emoji: '🦆' },
        { name: 'RoRo der Rote Panda', emoji: '🐾' },
        { name: 'Flauschball XL', emoji: '⚪' },
        { name: 'Kaffeetasse-Kuschel', emoji: '☕' },
        { name: 'Socken-Monster', emoji: '🧦' }
      ]
    },

    bauernhof: {
      name: 'Bauernhof',
      emoji: '🚜',
      gags: ['Singende Stalltür', 'Plastik-Ei', 'Regenjacke fürs Huhn', 'Gummi-Hufschuh', 'Mini-Silo mit Mütze'],
      items: [
        { name: 'Traktor', emoji: '🚜' },
        { name: 'Mähdrescher', emoji: '🚜' },
        { name: 'Hofkatze', emoji: '🐱' },
        { name: 'Wachhund Bello', emoji: '🐶' },
        { name: 'Milchkuh', emoji: '🐄' },
        { name: 'Fleckige Kuh', emoji: '🐄' },
        { name: 'Ziege', emoji: '🐐' },
        { name: 'Wolliges Schaf', emoji: '🐑' },
        { name: 'Hahn Kikeriki', emoji: '🐓' },
        { name: 'Huhn mit Ei', emoji: '🐔' },
        { name: 'Küken-Trio', emoji: '🐤' },
        { name: 'Pferd', emoji: '🐴' },
        { name: 'Mini-Pony', emoji: '🐴' },
        { name: 'Esel-Josef', emoji: '🫏' },
        { name: 'Schwein', emoji: '🐷' },
        { name: 'Ferkel-Bande', emoji: '🐖' },
        { name: 'Gänse-Marsch', emoji: '🪿' },
        { name: 'Truthahn', emoji: '🦃' },
        { name: 'Stall-Laterne', emoji: '🏮' },
        { name: 'Heuballen', emoji: '🌾' },
        { name: 'Wiese mit Klee', emoji: '🍀' },
        { name: 'Gartenzaun-Set', emoji: '🪵' },
        { name: 'Hühnerstall', emoji: '🏠' },
        { name: 'Scheune', emoji: '🏚️' },
        { name: 'Apfelbaum', emoji: '🍎' },
        { name: 'Birnenbaum', emoji: '🍐' },
        { name: 'Kirschbäumchen', emoji: '🍒' },
        { name: 'Gemüsebeet', emoji: '🥕' },
        { name: 'Kartoffelacker', emoji: '🥔' },
        { name: 'Kürbisfeld', emoji: '🎃' },
        { name: 'Erdbeerfeld', emoji: '🍓' },
        { name: 'Möhren-Beet', emoji: '🥕' },
        { name: 'Zucchini-Pflanze', emoji: '🥒' },
        { name: 'Tomaten-Pflanze', emoji: '🍅' },
        { name: 'Maiskolben', emoji: '🌽' },
        { name: 'Sonnenblumenwald', emoji: '🌻' },
        { name: 'Bienenstock', emoji: '🐝' },
        { name: 'Honigglas', emoji: '🍯' },
        { name: 'Milcheimer', emoji: '🥛' },
        { name: 'Butterfass', emoji: '🧈' },
        { name: 'Käse-Rad', emoji: '🧀' },
        { name: 'Mistgabel Deluxe', emoji: '🍴' },
        { name: 'Singende Stalltür', emoji: '🎶' },
        { name: 'Plastik-Ei', emoji: '🥚' },
        { name: 'Einfahrtsglocke', emoji: '🔔' },
        { name: 'Regenjacke fürs Huhn', emoji: '🧥' },
        { name: 'Gummi-Hufschuh', emoji: '👢' },
        { name: 'Mini-Silo mit Mütze', emoji: '🧢' },
        { name: 'Stroh-Frisur', emoji: '🌾' },
        { name: 'Bauernhof-Duftkarte', emoji: '🌬️' }
      ]
    },

    dinozoo: {
      name: 'Dino-Zoo',
      emoji: '🦖',
      gags: ['Dino-Fossil in Wackelpudding', 'Trikot für T-Rex', 'Echsen-Frisur', 'Dinosaurier-Schleim', 'Riesen-Beere'],
      items: [
        { name: 'T-Rex', emoji: '🦖' },
        { name: 'Triceratops', emoji: '🦖' },
        { name: 'Brachiosaurus', emoji: '🦕' },
        { name: 'Stegosaurus', emoji: '🦕' },
        { name: 'Velociraptor', emoji: '🦖' },
        { name: 'Ankylosaurus', emoji: '🦖' },
        { name: 'Pterodaktylus', emoji: '🪽' },
        { name: 'Dino-Ei', emoji: '🥚' },
        { name: 'Fossil vom T-Rex', emoji: '🦴' },
        { name: 'Zahn eines Raptors', emoji: '🦷' },
        { name: 'Dino-Fährte', emoji: '🐾' },
        { name: 'Urzeitvulkan', emoji: '🌋' },
        { name: 'Urwald-Pflanze', emoji: '🌿' },
        { name: 'Farnwald', emoji: '🍃' },
        { name: 'Dino-Baby', emoji: '🦕' },
        { name: 'Mutter mit Baby', emoji: '🦖' },
        { name: 'Dino-Ruf', emoji: '📞' },
        { name: 'Dino-Trampolin', emoji: '🤸' },
        { name: 'Dino-Eier-Nest', emoji: '🥚' },
        { name: 'Urzeit-Snack', emoji: '🫘' },
        { name: 'Dino-Picknick-Korb', emoji: '🧺' },
        { name: 'Zoo-Karte', emoji: '🗺️' },
        { name: 'Dino-Dompteur', emoji: '🤠' },
        { name: 'Gehege-Schlüssel', emoji: '🔑' },
        { name: 'Futtereimer', emoji: '🪣' },
        { name: 'Knochenschleuder', emoji: '🦴' },
        { name: 'Dino-Brille', emoji: '🕶️' },
        { name: 'Lava-Sandale', emoji: '🩴' },
        { name: 'Federn-Busch', emoji: '🪶' },
        { name: 'Baby-Dino-Rucksack', emoji: '🎒' },
        { name: 'Dino-Lied', emoji: '🎵' },
        { name: 'Gummischlange', emoji: '🐍' },
        { name: 'Dino-Schildkröten-Panzer', emoji: '🐢' },
        { name: 'Vulkanstein', emoji: '🪨' },
        { name: 'Zoo-Manager-Hut', emoji: '🎩' },
        { name: 'Dino-Fossil in Wackelpudding', emoji: '🍮' },
        { name: 'Trikot für T-Rex', emoji: '⚽' },
        { name: 'Plüsch-Dino-Deko', emoji: '🧸' },
        { name: 'Dino-Kinderwagen', emoji: '🛒' },
        { name: 'Riesen-Beere', emoji: '🫐' },
        { name: 'Urzeit-See', emoji: '🌊' },
        { name: 'Dino-Boot', emoji: '🚣' },
        { name: 'Stachel-Limette', emoji: '🍈' },
        { name: 'Echsen-Frisur', emoji: '🦎' },
        { name: 'Dino-Stempel', emoji: '🖊️' },
        { name: 'Dino-Zauberstab', emoji: '🪄' },
        { name: 'Mini-Dino-Figur', emoji: '🦖' },
        { name: 'Dinosaurier-Schleim', emoji: '🫧' },
        { name: 'Zoo-Besucher-Süßigkeiten', emoji: '🍭' },
        { name: 'Dino-Ausweis', emoji: '🪪' }
      ]
    },

    gruselhaus: {
      name: 'Gruselhaus',
      emoji: '👻',
      gags: ['Geist putzt Zähne', 'Grusel-Pommes', 'Leere Süßigkeiten-Tüte', 'Geisterkamera', 'Heulende Vase'],
      items: [
        { name: 'Freundliches Gespenst', emoji: '👻' },
        { name: 'Lachender Geist', emoji: '😄' },
        { name: 'Skelett im Schrank', emoji: '💀' },
        { name: 'Fledermaus-Paar', emoji: '🦇' },
        { name: 'Kobra im Korb', emoji: '🐍' },
        { name: 'Spinne an der Decke', emoji: '🕷️' },
        { name: 'Spinnennetz-Glanz', emoji: '🕸️' },
        { name: 'Kürbis-Gesicht', emoji: '🎃' },
        { name: 'Kürbislaterne', emoji: '🎃' },
        { name: 'Schwarze Katze', emoji: '🐈‍⬛' },
        { name: 'Eule im Turm', emoji: '🦉' },
        { name: 'Rabe mit Zettel', emoji: '🐦‍⬛' },
        { name: 'Alarm-Glocke', emoji: '🔔' },
        { name: 'Staubiger Spiegelschrank', emoji: '🪞' },
        { name: 'Knarzende Tür', emoji: '🚪' },
        { name: 'Nebelmaschine', emoji: '🌫️' },
        { name: 'Heulen im Wind', emoji: '💨' },
        { name: 'Geisterlicht', emoji: '💡' },
        { name: 'Mitternachtskürbis', emoji: '🌙' },
        { name: 'Wackelnde Treppe', emoji: '🪜' },
        { name: 'Fledermaus-Vorhang', emoji: '🪟' },
        { name: 'Alter Trank', emoji: '🧪' },
        { name: 'Zaubertrank-Flasche', emoji: '⚗️' },
        { name: 'Geisterstadt-Karte', emoji: '🗺️' },
        { name: 'Voodoo-Puppe', emoji: '🧵' },
        { name: 'Knochenbrücke', emoji: '🦴' },
        { name: 'Hexenkessel-Quirl', emoji: '🥄' },
        { name: 'Kuschel-Gespenst Decke', emoji: '🛏️' },
        { name: 'Geisterbild-Rahmen', emoji: '🖼️' },
        { name: 'Laterne mit Glühwürmchen', emoji: '🏮' },
        { name: 'Totenkopf-Überraschungsbox', emoji: '💀' },
        { name: 'Geisterhaus-Ticket', emoji: '🎫' },
        { name: 'Nebelhorn', emoji: '📯' },
        { name: 'Geister-Cola', emoji: '🥤' },
        { name: 'Grusel-Pommes', emoji: '🍟' },
        { name: 'Spuk-Glöckchen', emoji: '🔔' },
        { name: 'Geist putzt Zähne', emoji: '😁' },
        { name: 'Leere Süßigkeiten-Tüte', emoji: '🍬' },
        { name: 'Verschlucktes Schloss', emoji: '🔒' },
        { name: 'Geisterfedern', emoji: '🪶' },
        { name: 'Mond überm Turm', emoji: '🌕' },
        { name: 'Geisterbahn-Lichtkette', emoji: '✨' },
        { name: 'Katzenschrei-Video', emoji: '📺' },
        { name: 'Online-Spukpost', emoji: '💌' },
        { name: 'Geisterkamera', emoji: '📸' },
        { name: 'Skelett-Schaukel', emoji: '🪀' },
        { name: 'Grusel-Lampe Teddy', emoji: '🧸' },
        { name: 'Heulende Vase', emoji: '🏺' },
        { name: 'Schatten-Fuchs', emoji: '🦊' },
        { name: 'Dunst-Tröpfchen', emoji: '🌦️' }
      ]
    },

    zauberwelt: {
      name: 'Zauberwelt',
      emoji: '🧙',
      gags: ['Weggezauberte Socke', 'Zauberstab mit Frottee-Ende', 'Meisterfluch-Freundschaft', 'Kobold-Wetterballon', 'Zettel-Frosch'],
      items: [
        { name: 'Zauberstab', emoji: '🪄' },
        { name: 'Fliegender Besen', emoji: '🧹' },
        { name: 'Zauberhut', emoji: '🎩' },
        { name: 'Magischer Umhang', emoji: '🧥' },
        { name: 'Zaubertrank', emoji: '⚗️' },
        { name: 'Unsichtbarkeits-Shirt', emoji: '👕' },
        { name: 'Sprechender Spiegel', emoji: '🪞' },
        { name: 'Zauberbuch', emoji: '📖' },
        { name: 'Zaubersprüche-Sammlung', emoji: '📜' },
        { name: 'Glücksstein', emoji: '💎' },
        { name: 'Feuerschweif', emoji: '🔥' },
        { name: 'Eisestab', emoji: '❄️' },
        { name: 'Blitz-Zauber', emoji: '⚡' },
        { name: 'Regenmacher', emoji: '🌧️' },
        { name: 'Sternenstaub', emoji: '✨' },
        { name: 'Feen-Blume', emoji: '🌺' },
        { name: 'Einhorn-Tropfen', emoji: '🦄' },
        { name: 'Drachenflügel-Salbe', emoji: '🐉' },
        { name: 'Zaubertrank-Beutel', emoji: '👜' },
        { name: 'Kräuterkessel', emoji: '🍲' },
        { name: 'Zauberaxt des Weisen', emoji: '🪓' },
        { name: 'Konfetti-Magie', emoji: '🎊' },
        { name: 'Eulenpost', emoji: '🦉' },
        { name: 'Porträtblick', emoji: '🖼️' },
        { name: 'Hexenbesen-Parkplatz', emoji: '🅿️' },
        { name: 'Magischer Ring', emoji: '💍' },
        { name: 'Zauber-Schleife', emoji: '🎀' },
        { name: 'Versteckte Treppe', emoji: '🪜' },
        { name: 'Kristallkugel', emoji: '🔮' },
        { name: 'Magische Karten', emoji: '🃏' },
        { name: 'Abrakadabra-Truhe', emoji: '🧰' },
        { name: 'Feenstaub-Streuer', emoji: '🌠' },
        { name: 'Märchen-Wolke', emoji: '☁️' },
        { name: 'Zaubermuschel', emoji: '🐚' },
        { name: 'Mondlied-Trank', emoji: '🌙' },
        { name: 'Zauberteppich', emoji: '🕌' },
        { name: 'Gnom-Überraschung', emoji: '🧌' },
        { name: 'Troll-Picknick', emoji: '🧺' },
        { name: 'Königliches Zelt', emoji: '⛺' },
        { name: 'Milchstraßen-Magie', emoji: '🌌' },
        { name: 'Sprechender Zauberstab', emoji: '🎶' },
        { name: 'Meisterfluch-Freundschaft', emoji: '🤝' },
        { name: 'Weggezauberte Socke', emoji: '🧦' },
        { name: 'Zauberstab mit Frottee-Ende', emoji: '🧽' },
        { name: 'Zaubertopf-Suppe', emoji: '🍲' },
        { name: 'Regenbogen-Salz', emoji: '🌈' },
        { name: 'Kobold-Wetterballon', emoji: '🎈' },
        { name: 'Zettel-Frosch', emoji: '🐸' },
        { name: 'Zauberprüfung-Diplom', emoji: '🎓' },
        { name: 'Rückverwandlungs-Spiegel', emoji: '🪞' }
      ]
    },

    drachenland: {
      name: 'Drachenland',
      emoji: '🐉',
      gags: ['Reisepass für Drachen', 'Mini-Kompass', 'Drachengurke im Glas', 'Schuppenputz-Set', 'Feuerlöscher'],
      items: [
        { name: 'Feuerdrache', emoji: '🐉' },
        { name: 'Wasserdrache', emoji: '🐲' },
        { name: 'Baby-Drache', emoji: '🐉' },
        { name: 'Eisdrache', emoji: '❄️' },
        { name: 'Schattendrache', emoji: '🌑' },
        { name: 'Glitzerdrache', emoji: '✨' },
        { name: 'Sternendrache', emoji: '🌠' },
        { name: 'Wolkendrache', emoji: '☁️' },
        { name: 'Drachenei', emoji: '🥚' },
        { name: 'Drachenzahn-Halskette', emoji: '📿' },
        { name: 'Drachenflug-Umhang', emoji: '🪂' },
        { name: 'Feueratem-Handschuh', emoji: '🧤' },
        { name: 'Drachenschuppen-Rüstung', emoji: '🛡️' },
        { name: 'Drachenburg', emoji: '🏰' },
        { name: 'Goldschatz-Lager', emoji: '💰' },
        { name: 'Drachenhöhle', emoji: '⛰️' },
        { name: 'Lava-Fluss', emoji: '🌋' },
        { name: 'Flammende Berge', emoji: '🔥' },
        { name: 'Regenbogenfelsen', emoji: '🌈' },
        { name: 'Drachen-König', emoji: '👑' },
        { name: 'Eule als Gefährte', emoji: '🦉' },
        { name: 'Verzauberte Waffe', emoji: '⚔️' },
        { name: 'Drachen-Dudelsack', emoji: '🎵' },
        { name: 'Feuerteppich', emoji: '🧣' },
        { name: 'Drachen-Reitplatz', emoji: '🐴' },
        { name: 'Flug-Schule', emoji: '🎓' },
        { name: 'Drachenkind', emoji: '🐲' },
        { name: 'Schneckendrache', emoji: '🐌' },
        { name: 'Nebelwachtel', emoji: '🌫️' },
        { name: 'Donnerkeil', emoji: '⚡' },
        { name: 'Sturm-Drachen-Anhänger', emoji: '🌪️' },
        { name: 'Drachen-Laterne', emoji: '💡' },
        { name: 'Schlangenfell-Schild', emoji: '🐍' },
        { name: 'Drachentränenflasche', emoji: '🍾' },
        { name: 'Kobold-Freund', emoji: '🧌' },
        { name: 'Drachen-Schuppenschuh', emoji: '👞' },
        { name: 'Urfeuer-Karte', emoji: '🗺️' },
        { name: 'Drachenturm-Brille', emoji: '🔭' },
        { name: 'Drachenatem-Trainer', emoji: '💨' },
        { name: 'Goldene Drachenbrücke', emoji: '🌉' },
        { name: 'Schuppenputz-Set', emoji: '🧽' },
        { name: 'Drachenfutter-Box', emoji: '🥩' },
        { name: 'Feuerlöscher', emoji: '🧯' },
        { name: 'Glitzer-Drachenschuppe', emoji: '🛒' },
        { name: 'Mini-Kompass' , emoji: '🧭' },
        { name: 'Drachengurke im Glas', emoji: '🥒' },
        { name: 'Flügelpuder', emoji: '🦋' },
        { name: 'Reisepass für Drachen', emoji: '🛂' },
        { name: 'Drachenpost-Brieftaube', emoji: '🕊️' },
        { name: 'Glühwürmchen-Gruss', emoji: '🪲' }
      ]
    },

    weltraum: {
      name: 'Weltraum',
      emoji: '🚀',
      gags: ['Mondhund', 'Alien-Socken', 'Weltraum-Mineralwasser', 'Astronauten-Sonnenbrille', 'Raketen-Silvester'],
      items: [
        { name: 'Raumschiff', emoji: '🚀' },
        { name: 'Rakete', emoji: '🚀' },
        { name: 'Raumfähre', emoji: '🛸' },
        { name: 'Mondrover', emoji: '🌙' },
        { name: 'Marsmobil', emoji: '🔴' },
        { name: 'Astronautenanzug', emoji: '👨‍🚀' },
        { name: 'Helm mit Visier', emoji: '💫' },
        { name: 'Raumstation-ISS', emoji: '🛰️' },
        { name: 'Mondbasis', emoji: '🌕' },
        { name: 'Marskolonie', emoji: '👽' },
        { name: 'Sternenkaffee', emoji: '☕' },
        { name: 'Mondstaub-Probe', emoji: '🌌' },
        { name: 'Kometen-Schweif', emoji: '☄️' },
        { name: 'Asteroiden-Feld', emoji: '🪨' },
        { name: 'Saturn-Ringe', emoji: '🪐' },
        { name: 'Galaxien-Poster', emoji: '🌌' },
        { name: 'Teleskop', emoji: '🔭' },
        { name: 'Kometen-Sprungbrett', emoji: '⛰️' },
        { name: 'Alien mit drei Augen', emoji: '👽' },
        { name: 'Alien-Freund', emoji: '🛸' },
        { name: 'Roboter-Lauscher', emoji: '🤖' },
        { name: 'Schwerelose Kugel', emoji: '🔮' },
        { name: 'Space-Shuttle-Puzzle', emoji: '🧩' },
        { name: 'Raumstations-Knopf', emoji: '🪐' },
        { name: 'Mondglas', emoji: '🪣' },
        { name: 'Marsroboter-Kumpel', emoji: '🦾' },
        { name: 'Spacetaxi', emoji: '🚕' },
        { name: 'Sternengucker-Schemel', emoji: '🪑' },
        { name: 'Eisring-Armband', emoji: '💍' },
        { name: 'Galaxie im Glas', emoji: '🫙' },
        { name: 'Raum-Magnet', emoji: '🧲' },
        { name: 'Planeten-Überraschung', emoji: '🪐' },
        { name: 'Sonne im Bild', emoji: '🌞' },
        { name: 'Venus-Glühbirne', emoji: '💡' },
        { name: 'Kometen-Eis', emoji: '🍨' },
        { name: 'Raum-Zitronentee', emoji: '🍋' },
        { name: 'Astronautenschlafsack', emoji: '🛏️' },
        { name: 'Weltraum-Trainer', emoji: '🏋️' },
        { name: 'Sternbild-Karte', emoji: '🪐' },
        { name: 'Umlauf-Uhr', emoji: '⏰' },
        { name: 'Supernova-Feuerzeug', emoji: '🌟' },
        { name: 'Mondhund', emoji: '🐶' },
        { name: 'Orbit-Schaukel', emoji: '🛝' },
        { name: 'Alien-Socken', emoji: '🧦' },
        { name: 'Mondstaub im Tütchen', emoji: '🛍️' },
        { name: 'Raketen-Silvester', emoji: '🎆' },
        { name: 'Weltraum-Mineralwasser', emoji: '💧' },
        { name: 'Astronauten-Sonnenbrille', emoji: '🕶️' },
        { name: 'Schwerelos-Trainingsanzug', emoji: '👕' },
        { name: 'Raumschiff-Briefkasten', emoji: '📮' }
      ]
    },

    mittelalter: {
      name: 'Mittelalter',
      emoji: '🏰',
      gags: ['Ritterhelm aus Kochtopf', 'Leeres Weinfass', 'Münze im Bach', 'Strohmatratze', 'Rüdiger der Ritter'],
      items: [
        { name: 'Ritterrüstung', emoji: '🛡️' },
        { name: 'Ritterschwert', emoji: '⚔️' },
        { name: 'Schild mit Löwe', emoji: '🛡️' },
        { name: 'Helm', emoji: '🪖' },
        { name: 'Lanzenreiter', emoji: '🐴' },
        { name: 'Burgtor', emoji: '🚪' },
        { name: 'Zugbrücke', emoji: '🌉' },
        { name: 'Turmwächter', emoji: '🗼' },
        { name: 'Burgmauer', emoji: '🧱' },
        { name: 'Kerker-Schlüssel', emoji: '🔑' },
        { name: 'Fackel', emoji: '🔥' },
        { name: 'Fahne mit Drache', emoji: '🚩' },
        { name: 'Edelstein im Ring', emoji: '💎' },
        { name: 'Goldschatz', emoji: '💰' },
        { name: 'Königskrone', emoji: '👑' },
        { name: 'Königin-Diadem', emoji: '👸' },
        { name: 'Samt-Umhang', emoji: '🧥' },
        { name: 'Prinzessinnen-Kleid', emoji: '👗' },
        { name: 'Hofnarr', emoji: '🎪' },
        { name: 'Musikant', emoji: '🎻' },
        { name: 'Leierspielerin', emoji: '🎼' },
        { name: 'Barde mit Laute', emoji: '🪕' },
        { name: 'Markt-Krämer', emoji: '🥨' },
        { name: 'Schmied', emoji: '🔨' },
        { name: 'Amboss', emoji: '🪨' },
        { name: 'Wagenrad', emoji: '🏎️' },
        { name: 'Weinfass', emoji: '🛢️' },
        { name: 'Honig-Humpen', emoji: '🍯' },
        { name: 'Brotlaib', emoji: '🍞' },
        { name: 'Häuschen-Reihe', emoji: '🏘️' },
        { name: 'Marktstand', emoji: '🏪' },
        { name: 'Karren mit Heu', emoji: '🛒' },
        { name: 'Drache im Dienst', emoji: '🐉' },
        { name: 'Einhorn im Wald', emoji: '🦄' },
        { name: 'Turnier-Zelt', emoji: '⛺' },
        { name: 'Pfeil und Bogen', emoji: '🏹' },
        { name: 'Armbrust', emoji: '🔫' },
        { name: 'Suppen-Kessel', emoji: '🍲' },
        { name: 'Kerzenleuchter', emoji: '🕯️' },
        { name: 'Hufeisen-Glück', emoji: '🧲' },
        { name: 'Ritterhelm aus Kochtopf', emoji: '🍲' },
        { name: 'Leeres Weinfass', emoji: '🛢️' },
        { name: 'Königsbett-Vorhang', emoji: '🛏️' },
        { name: 'Seiden-Schal', emoji: '🧣' },
        { name: 'Strohmatratze', emoji: '🪑' },
        { name: 'Kräutergarten', emoji: '🌿' },
        { name: 'Turmglocke', emoji: '🔔' },
        { name: 'Münze im Bach', emoji: '🪙' },
        { name: 'Mini-Kutsche', emoji: '🛞' },
        { name: 'Rüdiger der Ritter', emoji: '🤺' }
      ]
    },

    schatzsuche: {
      name: 'Schatzsuche',
      emoji: '🗺️',
      gags: ['Goldmünze aus Schokolade', 'Piraten-Sandwich', 'Seeräuber-Parfüm', 'Leere Schatzkiste', 'Nebelkapitän'],
      items: [
        { name: 'Schatzkarte', emoji: '🗺️' },
        { name: 'Goldmünzen-Sack', emoji: '💰' },
        { name: 'Juwelenkiste', emoji: '💎' },
        { name: 'Rubin', emoji: '🔴' },
        { name: 'Smaragd', emoji: '🟢' },
        { name: 'Perlenkette', emoji: '📿' },
        { name: 'Silberlöffel', emoji: '🥄' },
        { name: 'Goldkrone', emoji: '👑' },
        { name: 'Kompass', emoji: '🧭' },
        { name: 'Fernrohr', emoji: '🔭' },
        { name: 'Taschenuhr', emoji: '⏰' },
        { name: 'Schatztruhe', emoji: '🪙' },
        { name: 'Münzschatz', emoji: '🏦' },
        { name: 'Perle der Tiefe', emoji: '🐚' },
        { name: 'Smaragd-See', emoji: '💚' },
        { name: 'Rubin-Riese', emoji: '❤️' },
        { name: 'Goldrücken-Schwert', emoji: '⚔️' },
        { name: 'Schatzkarte mit X', emoji: '❌' },
        { name: 'Dunkle Höhle', emoji: '⛰️' },
        { name: 'Leuchtturm-Schlüssel', emoji: '🗝️' },
        { name: 'Piratenhut', emoji: '🏴‍☠️' },
        { name: 'Augenklappe', emoji: '🕶️' },
        { name: 'Hakenhand-Pirat', emoji: '🦜' },
        { name: 'Papagei-Kumpel', emoji: '🦜' },
        { name: 'Säbel', emoji: '⚔️' },
        { name: 'Blasrohr', emoji: '🎋' },
        { name: 'Alte Pergamentrolle', emoji: '📜' },
        { name: 'Verfluchte Münze', emoji: '🪙' },
        { name: 'Goldfisch im Trank', emoji: '🐟' },
        { name: 'Taucherflosse', emoji: '🩱' },
        { name: 'Antike Peitsche', emoji: '🪢' },
        { name: 'Magnet-Pirat', emoji: '🧲' },
        { name: 'Ritter-Gold', emoji: '🛡️' },
        { name: 'Zauber-Kompass', emoji: '🧭' },
        { name: 'Drachentaler', emoji: '🐉' },
        { name: 'Schatzinsel', emoji: '🏝️' },
        { name: 'Verstecktes Dorf', emoji: '🏘️' },
        { name: 'Riesige Muschel', emoji: '🐚' },
        { name: 'Perlmutt-Schale', emoji: '⚪' },
        { name: 'Goldener Sand', emoji: '🏖️' },
        { name: 'Alte Landkarte', emoji: '📜' },
        { name: 'Nebelkapitän', emoji: '⛵' },
        { name: 'Leere Schatzkiste', emoji: '🧳' },
        { name: 'Goldmünze aus Schokolade', emoji: '🍫' },
        { name: 'Piraten-Sandwich', emoji: '🥪' },
        { name: 'Seeräuber-Parfüm', emoji: '🧴' },
        { name: 'Insel-Flasche', emoji: '📨' },
        { name: 'Kapitänsmütze', emoji: '⚓' },
        { name: 'Anker-Magnet', emoji: '⚓' },
        { name: 'Glücks-Oktopus', emoji: '🐙' }
      ]
    },

    unterwasser: {
      name: 'Unterwasser',
      emoji: '🐠',
      gags: ['Halber Schatz', 'Seegurken-Pudding', 'Taucherbrille ohne Glas', 'Sushi-Kiste', 'Muschelhorn'],
      items: [
        { name: 'Clownfisch', emoji: '🐠' },
        { name: 'Blaulippfisch', emoji: '🐟' },
        { name: 'Seepferdchen', emoji: '🐴' },
        { name: 'Qualle', emoji: '🪼' },
        { name: 'Korallenriff', emoji: '🪸' },
        { name: 'Anemone', emoji: '🌺' },
        { name: 'Seestern', emoji: '⭐' },
        { name: 'Muschel', emoji: '🐚' },
        { name: 'Perlmutt', emoji: '⚪' },
        { name: 'Riesenkrake', emoji: '🐙' },
        { name: 'Delfin', emoji: '🐬' },
        { name: 'Wal', emoji: '🐳' },
        { name: 'Blauwal-Baby', emoji: '🐋' },
        { name: 'Hai-Baby', emoji: '🦈' },
        { name: 'Seeschildkröte', emoji: '🐢' },
        { name: 'Meeresschildkröte', emoji: '🐢' },
        { name: 'Rochen', emoji: '🦈' },
        { name: 'Manta', emoji: '🪂' },
        { name: 'Kugelfisch', emoji: '🐡' },
        { name: 'Tanzende Scholle', emoji: '🐟' },
        { name: 'Seetangwald', emoji: '🌿' },
        { name: 'Seetang-König', emoji: '👑' },
        { name: 'Unterwasser-Vulkan', emoji: '🌋' },
        { name: 'Tiefseegraben', emoji: '⬇️' },
        { name: 'Gesunkenes Schiff', emoji: '🚢' },
        { name: 'Schatztruhe der See', emoji: '🪙' },
        { name: 'Goldbarren', emoji: '🟨' },
        { name: 'Seepferdchen-Sattel', emoji: '🚣' },
        { name: 'Taucherflossen', emoji: '🩱' },
        { name: 'Taucherbrille', emoji: '🤿' },
        { name: 'Sauerstoffflasche', emoji: '🫧' },
        { name: 'Leuchtkrakenlicht', emoji: '✨' },
        { name: 'Regenbogenfisch', emoji: '🐠' },
        { name: 'Meerjungfrau', emoji: '🧜‍♀️' },
        { name: 'Meerjungfrau-Krone', emoji: '👑' },
        { name: 'Meerjungfrau-Schwanz', emoji: '🧣' },
        { name: 'Botschaft in Flasche', emoji: '🍾' },
        { name: 'Korallenperle', emoji: '🪸' },
        { name: 'Glitzer-Plankton', emoji: '🌌' },
        { name: 'Korallen-Tempel', emoji: '🏛️' },
        { name: 'Muschelhorn', emoji: '📯' },
        { name: 'Tiefsee-Angler', emoji: '🎣' },
        { name: 'Taucherbrille ohne Glas', emoji: '🥽' },
        { name: 'Halber Schatz', emoji: '🪙' },
        { name: 'Seegurken-Pudding', emoji: '🥒' },
        { name: 'Marsch der Krabben', emoji: '🦀' },
        { name: 'Hummer-Duo', emoji: '🦞' },
        { name: 'Garnelen-Party', emoji: '🍤' },
        { name: 'Sushi-Kiste', emoji: '🍣' },
        { name: 'Perlenkönig-Ring', emoji: '💍' }
      ]
    },

    feuerwehr: {
      name: 'Feuerwehr',
      emoji: '🚒',
      gags: ['Papp-Hydrant', 'Brandübung-Schaum', 'Heldenumhang mit Flicken', 'Feuerspucker-Training', 'Rettungsgasse-Konfetti'],
      items: [
        { name: 'Feuerwehrauto', emoji: '🚒' },
        { name: 'Drehleiter', emoji: '🚒' },
        { name: 'Einsatzfahrzeug', emoji: '🚨' },
        { name: 'Rettungswagen', emoji: '🚑' },
        { name: 'Feuerwehr-Helikopter', emoji: '🚁' },
        { name: 'Feuerwehrboot', emoji: '🚤' },
        { name: 'Feuerlöscher', emoji: '🧯' },
        { name: 'Löschschlauch', emoji: '💦' },
        { name: 'Wassertank', emoji: '🛢️' },
        { name: 'Beil', emoji: '🪓' },
        { name: 'Spreizer', emoji: '🦾' },
        { name: 'Atemschutzmaske', emoji: '😷' },
        { name: 'Helm', emoji: '🪖' },
        { name: 'Einsatzjacke', emoji: '🧥' },
        { name: 'Feuerwehrstiefel', emoji: '👢' },
        { name: 'Leuchtweste', emoji: '🦺' },
        { name: 'Taschenlampe', emoji: '🔦' },
        { name: 'Funkgerät', emoji: '📻' },
        { name: 'Alarmsirene', emoji: '🚨' },
        { name: 'Glocke', emoji: '🔔' },
        { name: 'Hydrant', emoji: '🚿' },
        { name: 'Drehleiter-Korb', emoji: '🧺' },
        { name: 'Brandschutz-Schild', emoji: '🖌️' },
        { name: 'Notfall-Picknick', emoji: '🥪' },
        { name: 'Feuerwehr-Dackel', emoji: '🐕' },
        { name: 'Brandmelder', emoji: '💥' },
        { name: 'Thermometer', emoji: '🌡️' },
        { name: 'Rauchmelder', emoji: '💨' },
        { name: 'Türöffnungshammer', emoji: '🔨' },
        { name: 'Kettensäge', emoji: '🪚' },
        { name: 'Sicherheitsnetz', emoji: '🥅' },
        { name: 'Feuerwehr-Plakat', emoji: '📢' },
        { name: 'Ehrenmedaille', emoji: '🎖️' },
        { name: 'Retter-Umhang', emoji: '🧡' },
        { name: 'Reserve-Helm', emoji: '🪖' },
        { name: 'Blaulicht-Sticker', emoji: '🚨' },
        { name: 'Feuerwehr-Café-Gutschein', emoji: '☕' },
        { name: 'Mini-Löschfahrzeug', emoji: '🚒' },
        { name: 'Signalgong', emoji: '🔔' },
        { name: 'Feuerschnüffler', emoji: '👃' },
        { name: 'Papp-Hydrant', emoji: '📦' },
        { name: 'Heldenumhang mit Flicken', emoji: '🪡' },
        { name: 'Brandübung-Schaum', emoji: '🫧' },
        { name: 'Rettungs-Karte', emoji: '🛤️' },
        { name: 'Löschturm', emoji: '🗼' },
        { name: 'Alarm-Hose', emoji: '👖' },
        { name: 'Feuerspucker-Training', emoji: '🔥' },
        { name: 'Flammen-Adventskranz', emoji: '🎄' },
        { name: 'Glut-Ofen', emoji: '🔥' },
        { name: 'Rettungsgasse-Konfetti', emoji: '🎉' }
      ]
    },

    werkstatt: {
      name: 'Werkstatt',
      emoji: '🔧',
      gags: ['Zollstock mit Kringel', 'Glitzer-Schraube', 'Schlüssel-Waschmaschine', 'Werkstatt-Schild', 'Abgas-Absauger'],
      items: [
        { name: 'Schraubenschlüssel', emoji: '🔧' },
        { name: 'Schraubenzieher', emoji: '🪛' },
        { name: 'Hammer', emoji: '🔨' },
        { name: 'Zange', emoji: '🥢' },
        { name: 'Wasserwaage', emoji: '📏' },
        { name: 'Maßband', emoji: '📐' },
        { name: 'Säge', emoji: '🪚' },
        { name: 'Bohrmaschine', emoji: '🔩' },
        { name: 'Schleifmaschine', emoji: '🛠️' },
        { name: 'Schweißgerät', emoji: '⚡' },
        { name: 'Tacker', emoji: '📎' },
        { name: 'Cutter-Messer', emoji: '🔪' },
        { name: 'Schutzkappe', emoji: '🎩' },
        { name: 'Arbeitshandschuhe', emoji: '🧤' },
        { name: 'Kniepolster', emoji: '🦵' },
        { name: 'Sicherheitsbrille', emoji: '🥽' },
        { name: 'Warnweste', emoji: '🦺' },
        { name: 'Werkbank', emoji: '🪑' },
        { name: 'Schraubstock', emoji: '🔧' },
        { name: 'Schubladenbox', emoji: '🗄️' },
        { name: 'Werkzeugkiste', emoji: '🧰' },
        { name: 'Akkuschrauber', emoji: '🪛' },
        { name: 'Stehleiter', emoji: '🪜' },
        { name: 'Eimer mit Mörtel', emoji: '🪣' },
        { name: 'Zollstock', emoji: '📏' },
        { name: 'Reifen-Pumpe', emoji: '🎈' },
        { name: 'Ölkanne', emoji: '🛢️' },
        { name: 'Brechstange', emoji: '🪵' },
        { name: 'Dübelbox', emoji: '📦' },
        { name: 'Nägel-Beutel', emoji: '🪙' },
        { name: 'Fahrradschlauch', emoji: '🚲' },
        { name: 'Feilen-Set', emoji: '🛠️' },
        { name: 'Sandpapier-Stapel', emoji: '📄' },
        { name: 'Klebstoff-Kanon', emoji: '🔫' },
        { name: 'Hitzepistole', emoji: '🔥' },
        { name: 'Zement-Tüte', emoji: '🟫' },
        { name: 'Betonmischer', emoji: '🎚️' },
        { name: 'Schubkarre', emoji: '🧺' },
        { name: 'Schweißerhelm', emoji: '🪖' },
        { name: 'Feuerschutzdecke', emoji: '🧣' },
        { name: 'Zollstock mit Kringel', emoji: '🌀' },
        { name: 'Glitzer-Schraube', emoji: '✨' },
        { name: 'Blaue Drahtrolle', emoji: '💙' },
        { name: 'Rote Drahtrolle', emoji: '❤️' },
        { name: 'Schlüssel-Waschmaschine', emoji: '🔑' },
        { name: 'Elektrotestgerät', emoji: '🔦' },
        { name: 'Rohrzange', emoji: '🔧' },
        { name: 'Werkstatt-Schild', emoji: '🚪' },
        { name: 'Mini-Lastwagen', emoji: '🚚' },
        { name: 'Abgas-Absauger', emoji: '💨' }
      ]
    },

    sport: {
      name: 'Sportstadion',
      emoji: '⚽',
      gags: ['Medaille aus Weichplastik', 'Ski-Pasta', 'Rundkurs-Schnecke', 'Werbebande', 'Siegerpose-Foto'],
      items: [
        { name: 'Fußball', emoji: '⚽' },
        { name: 'Handball', emoji: '🤾' },
        { name: 'Basketball', emoji: '🏀' },
        { name: 'Volleyball', emoji: '🏐' },
        { name: 'Tennisball', emoji: '🎾' },
        { name: 'Tischtennisball', emoji: '🏓' },
        { name: 'Golfball', emoji: '⛳' },
        { name: 'Dartscheibe', emoji: '🎯' },
        { name: 'Bowlingkugel', emoji: '🎳' },
        { name: 'Baseballschläger', emoji: '🥎' },
        { name: 'Federball', emoji: '🏸' },
        { name: 'Bogenschießen-Set', emoji: '🏹' },
        { name: 'Ruder-Gerät', emoji: '🚣' },
        { name: 'Laufband', emoji: '🏃' },
        { name: 'Fahrrad', emoji: '🚴' },
        { name: 'Skateboard', emoji: '🛹' },
        { name: 'Eisstockschießen', emoji: '🥌' },
        { name: 'Ski', emoji: '🎿' },
        { name: 'Snowboard', emoji: '🏂' },
        { name: 'Schlittschuhe', emoji: '⛸️' },
        { name: 'Boxhandschuhe', emoji: '🥊' },
        { name: 'Schwimmbrille', emoji: '🥽' },
        { name: 'Springseil', emoji: '🪢' },
        { name: 'Hanteln', emoji: '🏋️' },
        { name: 'Turnmatte', emoji: '🤸' },
        { name: 'Trampolin', emoji: '🤾' },
        { name: 'Triathlon-Shirt', emoji: '👕' },
        { name: 'Medaille Gold', emoji: '🥇' },
        { name: 'Medaille Silber', emoji: '🥈' },
        { name: 'Medaille Bronze', emoji: '🥉' },
        { name: 'Pokal', emoji: '🏆' },
        { name: 'Siegerkranz', emoji: '🏅' },
        { name: 'Fan-Mütze', emoji: '🧢' },
        { name: 'Eintrittskarte', emoji: '🎫' },
        { name: 'Tribünen-Platz', emoji: '🪑' },
        { name: 'Schiedsrichter-Pfeife', emoji: '📯' },
        { name: 'Linienkalk', emoji: '🥛' },
        { name: 'Rasensamen', emoji: '🌱' },
        { name: 'Sport-Kappe', emoji: '⛑️' },
        { name: 'Staffelstab', emoji: '🥢' },
        { name: 'Springstange', emoji: '🎋' },
        { name: 'Tor auf Zeit', emoji: '⏲️' },
        { name: 'Medaille aus Weichplastik', emoji: '🏅' },
        { name: 'Ski-Pasta', emoji: '🍝' },
        { name: 'Rundkurs-Schnecke', emoji: '🐌' },
        { name: 'Fanfare', emoji: '📣' },
        { name: 'Werbebande', emoji: '🚧' },
        { name: 'Flutlicht', emoji: '💡' },
        { name: 'Siegerpose-Foto', emoji: '📸' },
        { name: 'Glücksball-Regen', emoji: '⚪' }
      ]
    },

    robo: {
      name: 'Roboterfabrik',
      emoji: '🤖',
      gags: ['Roboter mit Ladefehler', 'Schrauben-König', 'Akustik-Robo', 'Klebstoff-Roboter', 'Rotierender Arm'],
      items: [
        { name: 'Haushaltsroboter', emoji: '🤖' },
        { name: 'Küchenroboter', emoji: '🍳' },
        { name: 'Saugroboter', emoji: '🧹' },
        { name: 'Robo-Assistent', emoji: '🤖' },
        { name: 'Robo-Hund', emoji: '🐕' },
        { name: 'Robo-Katze', emoji: '🐈' },
        { name: 'Robo-Fisch', emoji: '🐠' },
        { name: 'Robo-Auto', emoji: '🚗' },
        { name: 'Robo-Rakete', emoji: '🚀' },
        { name: 'Robo-Dino', emoji: '🦖' },
        { name: 'Bauteil-Box', emoji: '🧰' },
        { name: 'Schaltgetriebe', emoji: '⚙️' },
        { name: 'Platine', emoji: '🟩' },
        { name: 'Chip-Überraschung', emoji: '🔌' },
        { name: 'Mini-CPU', emoji: '🖥️' },
        { name: 'Roboter-Arm', emoji: '🦾' },
        { name: 'Roboter-Bein', emoji: '🦿' },
        { name: 'Augen-LED', emoji: '👀' },
        { name: 'Akku-Block', emoji: '🔋' },
        { name: 'Solarpanel', emoji: '☀️' },
        { name: 'Drahtspule', emoji: '🔀' },
        { name: 'Getriebe-Schalter', emoji: '🔛' },
        { name: 'Ladeschale', emoji: '⚡' },
        { name: 'Werkzeug-Set', emoji: '🔧' },
        { name: 'Robo-Farbe Blau', emoji: '🔵' },
        { name: 'Robo-Farbe Rot', emoji: '🔴' },
        { name: 'Stickerbogen', emoji: '🏷️' },
        { name: 'Robo-Programmierkarte', emoji: '💾' },
        { name: 'Bausatz-Box', emoji: '🧩' },
        { name: 'Roboter-Schutzhelm', emoji: '⛑️' },
        { name: 'Robo-Glöckchen', emoji: '🔔' },
        { name: 'Robo-Musik-Box', emoji: '🎵' },
        { name: 'KI-Buch', emoji: '📚' },
        { name: 'Robo-Zertifikat', emoji: '📜' },
        { name: 'Fabrik-Plan', emoji: '🗺️' },
        { name: 'Generator', emoji: '🧲' },
        { name: 'Spiritus-Brenner', emoji: '🔥' },
        { name: 'Lötstation', emoji: '🔥' },
        { name: 'Messgerät', emoji: '📟' },
        { name: 'Wärmebildkamera', emoji: '📷' },
        { name: 'Roboter mit Ladefehler', emoji: '🔋' },
        { name: 'Roboter-Schulranzen', emoji: '🎒' },
        { name: 'Mini-Roboter-Figur', emoji: '🤖' },
        { name: 'Robo-T-Shirt', emoji: '👕' },
        { name: 'Klebstoff-Roboter', emoji: '🧴' },
        { name: 'Robo-Kopfschutz', emoji: '🎧' },
        { name: 'Rotierender Arm', emoji: '🔄' },
        { name: 'Schrauben-König', emoji: '👑' },
        { name: 'Akustik-Robo', emoji: '📢' },
        { name: 'Robo-Schlüsselband', emoji: '📿' }
      ]
    }
  };

  // Anzeige- und Auswahlreihenfolge: thematisch gruppiert (Essen, Tiere,
  // Fantasie, Technik), Freizeitpark als Kirmes-Klassiker vornweg.
  const CATEGORY_ORDER = [
    'freizeitpark',
    'pizzeria',
    'doener',
    'burger',
    'naschwerk',
    'eisdiele',
    'bauernhof',
    'dinozoo',
    'kuscheltiere',
    'unterwasser',
    'gruselhaus',
    'zauberwelt',
    'drachenland',
    'mittelalter',
    'schatzsuche',
    'weltraum',
    'robo',
    'feuerwehr',
    'werkstatt',
    'sport'
  ];

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { CATEGORIES, CATEGORY_ORDER };
  } else {
    window.CATEGORIES = CATEGORIES;
    window.CATEGORY_ORDER = CATEGORY_ORDER;
  }
})();